include:
  - project: 'jamalex-ltd/finan/finan-be/ci-image'
    ref    : 'add-stg-env'
    file   : 'ci-templates/base.yml'

variables:
  SERVICE: "${CI_PROJECT_NAME}"
  APP_NAME: finan
  VERSION: "${CI_COMMIT_REF_NAME}"

docker_build:
  extends: .docker_build

tag_release:
  extends: .tag_release

deploy:dev:
  variables:
    APP_ENV: dev
    DB_NAME: "finan_dev_ms_order_management"

deploy:stg:
  variables:
    APP_ENV: stg
    DB_NAME: "finan_stg_ms_order_management"

deploy:prd:
  variables:
    APP_ENV: prd
    DB_NAME: "finan_prd_ms_order_management"
